### ISSUE TITLE
The script doesn't work, i get this warning : "Can't load Mono.Cecil.Reflexil.dll, press any key to exit..."

### ISSUE THREAD

**Issue by CrikMundo** [beatcracker/Ori-Controller-Remap#1]
The script file doesn't work... i get this warning : "Can't load Mono.Cecil.Reflexil.dll, press any key to exit..."

I run Ori in Steam and under Windows 10. Tried to map my logitech dual action pad with Pinacle and the gamepad configuration doesn't even change inside the game. Tried to click-shift on the executable file and change every button as it is told in Steam discussion... won't help either.

Is it just possible to get a Dual Action pad from Logitech to work with this game?

Thx for your help!

**Comment by beatcracker** [comment]
Try to unblock zip file before unpacking: http://blogs.msdn.com/b/delay/p/unblockingdownloadedfile.aspx

Looks like I've updated how-to on [Steam Community post](https://steamcommunity.com/app/261570/discussions/0/530646080852232829/), but forgot to do it here.

**Comment by CrikMundo** [comment]
Thank you so much for your fast response! 
Ok I Unblocked it as you showed me and I got farther in the process but I get now lots of red messages. I took a screen capture. See the attached file.

Is this an issue or am I still doing something wrong?

Thanks!

![capturewarning1](https://cloud.githubusercontent.com/assets/16940585/12649799/185dbb28-c5ae-11e5-91ea-b807e5fc660f.PNG)

**Comment by beatcracker** [comment]
Looks like you have to install .Net Framework 3.5. You can do this via Windows GUI or command line.

### Command line
- Run `cmd.exe` or `PowerShell.exe` as Administrator
- Copy/Paste text below and press `Enter`:
- `DISM /Online /Enable-Feature /FeatureName:NetFx3 /All`

### Windows GUI
- Press `Windows Logo` + `R` keys on the keyboard.
- Type `appwiz.cpl` in the `Run` command box and press `ENTER`.
- In the `Programs and Features` window, click on the link `Turn Windows features on or off`.
- Check if the `.NET Framework 3.5 (includes .NET 2.0 and 3.0)` option is available in it.
- If yes, then enable it and then click on `OK`.
- Follow the on-screen instructions to complete the installation and restart the computer, if prompted.

**Comment by CrikMundo** [comment]
I'm running the command line in the cmd.exe file... it's loading. I'll post as soon as it is finished. :)

**Comment by CrikMundo** [comment]
YESS!!!! The script worked! You're a genius! Here is the screen capture : 
![capturesuccespatching](https://cloud.githubusercontent.com/assets/16940585/12650466/f76a8ce0-c5b0-11e5-8a0c-01a4c08fa788.PNG)

Now i'll test the game.

Thank you so much!

**Comment by CrikMundo** [comment]
OMG it's working! I really though it would never work.

You've made my day thank you! :)

**Comment by CrikMundo** [comment]
Think I called it a victory too soon...

Sorry to say that... the 4 buttons now work and the menu and map as well. But the RT and LT buttons don't. They just don't seem to be mapped... It's buttons 5 to 8 on the Dual action gamepad. 

Any clue? :(

(The physical buttons themself are working fine because before the patch the button 7 would trigger the map and the button 8 would trigger the menu...)

**Comment by beatcracker** [comment]
Judging from your screenshot, Logitech Dual Action pad uses same mapping as my Cyborg Rumble pad, so it shoud work. Make sure that you have no remapped buttons in Logitech Gaming Software, Pinnacle Game Profiler or Unity's built-in remapper. To clear Unity bindings for Ori and The Blind Forest see [this post](http://steamcommunity.com/app/261570/discussions/0/492379439671473764/).

**Comment by CrikMundo** [comment]
i used Joy toKey to remap the buttons 7 and 8 to up and shift key and now it's working.

Whoa at last!

Thank you again for all your patience and support!

**Comment by Susexe** [comment]
I have the same problem, LT and RT buttons cannot be remmaped. On my Chinese copy of PS2 gamepad, LT and RT are mapped on the left and right directions of the right analog stick when analog button is turned on, which is unaplayable. I tried the other more basic controller without analog sticks and this time I couldn't even execute LT and RT commands. Do you know what could be the problem?

Thanks, CrikMundo, for JoytoKey. It worked great.

**Comment by beatcracker** [comment]
I've totally forgot, but non-working triggers were already reported in [Steam community thread](https://steamcommunity.com/app/261570/discussions/0/530646080852232829/#c537405286641246722) and `JoyToKey` seems to be fixing it. Since I can't get my hands on a gamepad that exhibits this behavior, I can't debug it, so I advice you to use `JoyToKey` for now.

I've also updated readme with info about `.Net Framework 3.5` , `JoyTokey` fix for triggers and added some more controller mappings to `Ori_Controller_Remap.ini` file. Feel free to open new issues if something doesn't work.

Cheers!
