### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by aroidzap** [beatcracker/Ori-Controller-Remap#2]
Hi, you should add this to FAQ :)

Q: The script file doesn't work... i get this warning : "Can't load Mono.Cecil.Reflexil.dll, press any key to exit..."
A: Try to unblock zip file before unpacking: http://blogs.msdn.com/b/delay/p/unblockingdownloadedfile.aspx

**Comment by beatcracker** [comment]
Sure, why not.
