### ISSUE TITLE
I have error

### ISSUE THREAD

**Issue by uitlaber** [beatcracker/Ori-Controller-Remap#6]
Join-Path : Не удается привязать аргумент к параметру "Path", так как он имеет значение NULL.

**Comment by beatcracker** [comment]
Hi there!

Looks like the script can't find game installation path. Do you have an original, non-definitive edition? Those a quite rare now :). For definitive edition you don't need this patch: http://steamcommunity.com/app/387290/discussions/0/364040166669190939/

**Comment by uitlaber** [comment]
No this cracked version :)
