### ISSUE TITLE
missing dll?

### ISSUE THREAD

**Issue by bjsmegma** [beatcracker/Ori-Controller-Remap#7]
Powershell says: WARNING: Can't find Assembly-CSharp.dll in

I'm not familiar with what this file does, or where it should be located. How can I fix this?

**Comment by beatcracker** [comment]
Hi there!

This means that the script was able to get Ori installation directory from registry, but there is no `Assembly-CSharp.dll` in `ori_Data\Managed` subfolder. This file is a part of the game that should be patched.

P.S. Do you have an original, non-definitive edition? Those a quite rare now :). For definitive edition you don't need this patch: http://steamcommunity.com/app/387290/discussions/0/364040166669190939/
