### ISSUE TITLE
New game Ori DE, missed registry folder

### ISSUE THREAD

**Issue by Talissera** [beatcracker/Ori-Controller-Remap#8]
Since the only game version to buy is Ori and the Blind Forest DE, there is new registry folder:
Steam App 387290
Still even with this fix it doesn't work. DualShock 3 (USB), SCP Toolkit/x360ce.

**Comment by beatcracker** [comment]
[Ori and the Blind Forest: Definitive Edition](http://store.steampowered.com/app/387290) supports [native controller remapping](http://steamcommunity.com/app/387290/discussions/0/364040166669190939/). Use this tool only if you have original, non-Definitive edition.
